# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# React Native New Architecture
newArchEnabled=true
hermesEnabled=true

# CMake: force 3.31.6 to fix CMake 3.22 + NDK r27 + Prefab bug
android.cmake.version=3.31.6
