# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1g
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# React Native New Architecture
newArchEnabled=false
hermesEnabled=true

# Dawai Release Signing (يُضاف عند الـ release)
# DAWAI_UPLOAD_STORE_FILE=dawai-release.keystore
# DAWAI_UPLOAD_STORE_PASSWORD=
# DAWAI_UPLOAD_KEY_ALIAS=dawai
# DAWAI_UPLOAD_KEY_PASSWORD=
