export const Colors = {
  primary       : '#E91E8C',
  primaryDark   : '#C2177A',
  primaryLight  : '#F48DBE',
  primaryGlow   : '#FFF0F8',
  secondary     : '#1A1A2E',
  secondaryLight: '#2D2D44',
  success       : '#10B981',
  successLight  : '#D1FAE5',
  warning       : '#F59E0B',
  warningLight  : '#FEF3C7',
  error         : '#EF4444',
  errorLight    : '#FEE2E2',
  info          : '#3B82F6',
  infoLight     : '#DBEAFE',
  white         : '#FFFFFF',
  black         : '#000000',
  background    : '#F8F9FC',
  surface       : '#FFFFFF',
  surfaceAlt    : '#F3F4F6',
  border        : '#E5E7EB',
  borderLight   : '#F3F4F6',
  textPrimary   : '#1F2937',
  textSecondary : '#6B7280',
  textHint      : '#9CA3AF',
  textDisabled  : '#D1D5DB',
  overlay       : 'rgba(0,0,0,0.5)',
  overlayLight  : 'rgba(0,0,0,0.3)',
};
